### PR TITLE
Handle string parameters in delete correctly in Python 3

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@BY-jk Can you give me a hint on how/where to write a test for this?

**Comment by jank** [comment]
First, I would have a look at which parts of delete are tested by the sqlalchemy test suite: https://github.com/zzzeek/sqlalchemy/blob/abeea1d82db34232bbef01e98fa4d1de0f583eb6/test/sql/test_delete.py

If not fully covered, delete tests should be added as test_delete.py following the Update Test example https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/test/test_update.py

**Comment by jank** [comment]
One question: did something broke on executing the previous code path (without proper p3k string handling)?
Reason I am asking is: reading through the comment on the pre_exec method, we potentially carry forward legacy code if the prepare performance for delete got improved in recent EXASOL versions.

**Comment by xhochy** [comment]
It did break on Python 3 when I passed an `str` value. In Python 2 you can call decode on `str` as it is a bytes-like, in Python 3 you cannot.

Regarding the necessity of this section of code I cannot sadly say anything. In my use case, this code path is only used for a small set of data.

**Comment by xhochy** [comment]
The delete tests in https://github.com/zzzeek/sqlalchemy/blob/abeea1d82db34232bbef01e98fa4d1de0f583eb6/test/sql/test_delete.py don't seem to be executed in Travis. They should be sufficient to detect the problem I've fixed. Sadly I don't understand how the test are discovered through the magic of indirect imports.

**Comment by jank** [comment]
I'll have a look - there is indeed quite some logic involved in determining the test set per dialect.

**Comment by jank** [comment]
This testing setup requires two PhDs minimum. I'll go ahead and merge this. I will carry out compensating commits afterwards if required.

**Pull request merged**
