### PR TITLE
Fixing remaining issues of odbc metadata queries

### LINKED ISSUE #89: Avoid DB locks when performing metadata queries on SYS tables
The default locking behavior of Exasol is to create table locks. 

When running queries with a high degree of concurrent connections on the same tables, deadlock situations can occur. This can be observed, e.g. when using BI tools that excessively query metadata tables.

To avoid deadlocks with pure read queries, select statements on SYS tables should be prepended with the DB hint `/*snapshot execution*/`. Starting with Exasol 6.2.5 the DB will execute these statements in a snapshot isolation mode, effectively avoiding creation of locks.

The idea for implementation is to prepend select statements on SYS tables with the pseudo comment `/*snapshot execution*/`.

Things to clarify & explore before implementation:

* details on the snapshot execution feature documented here https://www.exasol.com/support/browse/EXASOL-2646
* what is the DB version of the test DB?
* should the pseudo comment only be generated for DB versions >= 6.2.5 or even for older versions (that will ignore this comment)?
* how can this be tested given that the deadlock situations only occur in situations of excessive concurrency? (e.g. are they ways to inspect the query plan to check if snapshot isolation is active)
* which type of queries should be covered (e.g. only SELECT)?
* how should queries be treated that query/merge other tables besides tables residing in `SYS`?
* what are potential side-effects on the SQLA test suite that heavily uses metadata queries to test the effects of DDL statements, e.g. are the changes to the data catalog visible when running in snapshot isolation?
* potential places for implementation
  * the pre_exec() method could be a potential place for the injection: https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/sqlalchemy_exasol/base.py#L336
  * the reflection methods of the EXADialect class (e.g. manually insert the pseudo comment to all select statements) https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/sqlalchemy_exasol/base.py#L375
* consider using the prefix_with() method available on all selectables https://docs.sqlalchemy.org/en/13/core/selectable.html?highlight=prefix#sqlalchemy.sql.expression.Select.prefix_with

### PR DESCRIPTION
**Pull request by tkilias**
This is continuation of pull request #90 and fixes the remaining test failures. 

Closes #89

### CODE REVIEW

**Comment by tkilias** [comment]
@BY-jk So, I now got all tests green. There were still some edge cases left which made trouble, but now it should be fine. The previous pull request #90 got closed, probably by an accidental push to master, which I reverted within a minute. If you are ok with this state, I would merge it to master, and then we can discuss, how we get this to PyPi.

**Comment by jank** [comment]
@tkilias excellent work. Please go ahead and merge to master.
I discussed with @nndo1991 how to proceed.
Here is the plan of attac:
* a 2.1.0 release that includes: the odbc metadata query changes, switch from Travis to GitHub actions
* a 3.0.0 release later (not urgent) that will drop Python 2.7 support and bump dependencies (e.g. like turbodbc) to their latest releases again

@nndo1991 is working on getting the GitHub Action workflow ready to release.

**Comment by fergarzag91** [comment]
Hi @tkilias is this the final version of your odbc changes or still planning to do more? I'm almost done on the Github Actions setup in my forked repo and will work on releasing 2.1.0 in the next couple of days.

**Comment by tkilias** [comment]
Hi @nndo1991, that is for the near future the final version. It avoids for pyodbc the deadlocks for all metadata functions. It shows for the tests the same behavior as the previous implementation and I specifically added tests to compare their results and to check the deadlocks behavior. The only difference happens in case of concurrent DDL operations, but this is normal for snapshot behavior. We are also thinking about a general solution within the database core, but this  will take a while. So, from my side you can publish the current state. Thx.

**Pull request merged**
