### PR TITLE
Cleanup bash magic in GitHub Actions and replace with properties

### PR DESCRIPTION
**Pull request by tkilias**

### CODE REVIEW

**Review by fergarzag91 — COMMENTED** [review]
Hi @tkilias just have one question regarding this new Workflow:

Are we now executing 100% of this steps on the Exasol Docker environment, or is the py.test command in the last step still being executed in the test DB previously provided by Exasol?

**Comment by tkilias** [comment]
> Hi @tkilias just have one question regarding this new Workflow:
> 
> Are we now executing 100% of this steps on the Exasol Docker environment, or is the py.test command in the last step still being executed in the test DB previously provided by Exasol?

Hi @nndo1991,

the py.test command uses to 100% the Exasol Docker environment. I actually wouldn't be able to use the Exasol provided DB in case would want use it, because I don't have credentials for it.

[Here](https://github.com/blue-yonder/sqlalchemy_exasol/blob/f91503377d18d7cd01cf25f9871859940801d197/.github/workflows/main.yml#L82) I defined the SQLAlchemy URL and as you probably can see, it only uses localhost which is the docker environment. 

However, when I looked at it, I got an idea. The docker environment supports multiple Exasol versions. You can select the version with --docker-db-image-version. Might be a good idea, to add a few versions to the matrix strategy. What do you think about this?

**Comment by fergarzag91** [comment]
Thank you @tkilias 

What do you think about the multiple Exasol versions @BY-jk? Not sure if the overhead of adding more versions to the Github action is worth the extra benefit. Do we support multiple versions inside BY?

**Comment by tkilias** [comment]
Hi @nndo1991 and @BY-jk,

I tried to add build jobs with multiple Exasol version. I had to add a newer bugfix version for 6.0 to the docker environment, but after that the SQLAlchemy passed all tests. So, it works for the following Exasol versions: 6.2.6, 6.2.5, 6.2.4, 6.1.6, 6.0.16

It didn't work for 6.0.13 and downwards, 6.0.14 and 15 I didn't test until now (need to add support for these version to the docker environment first). For 6.1, I also need to add support for the newer version to the docker environment, but I assume if it works for 6.1.6, then the newer will probably work as well.

You can find the build [here](https://github.com/tkilias/sqlalchemy_exasol/actions/runs/116173909)

**Comment by jank** [comment]
The previous centrally hosted DB we were testing against is running on 6.1.rc2.

I would suggest to align with the EXASOL life cycle published here and always test the latest 2-3 supported versions: https://www.exasol.com/portal/display/DOWNLOAD/Exasol+Life+Cycle

E.g. at the time of writing this, test against the latest 6.0.16, 6.1.6 and 6.2.6 and bump those to the latest version whenever one becomes available. Once 7.0 is published, 6.0.x could be dropped from the build matrix.

Any opinions?

**Comment by tkilias** [comment]
@BY-jk sounds good for me. I will add the newest 6.1 version to the docker environment , adapt the matrix strategy and open a pull request.

**Comment by tkilias** [comment]
@BY-jk @nndo1991 So, in case you want to test against the latest bugfix versions for all supported Exasol minor versions, I made a pull request for that. https://github.com/blue-yonder/sqlalchemy_exasol/pull/96

**Pull request merged**
