### PR TITLE
#110: Add job name to github workflow

### LINKED ISSUE #110: Add job name to .github/workflows/CI-CD.yml
github-keeper can only update the branch protection in this repo if a job name is defined in `.github/workflows/CI-CD.yml`:

`Validation Error for .github/workflows/CI-CD.yml: multi dimensional matrix github-action jobs with no explicit name are not supported. Please add a name field to the job that combines the matrix parameters into a more readable name. For example "Build with Go ${{matrix.go}} and Exasol ${{ matrix.db }}"`

### PR DESCRIPTION
**Pull request by Nicoretti**
- Add InteliJ based IDE config folders to .gitignore
- Add explicit names for matrix based github action jobs

In order to automatically maintain the configuration of the github repository,
with the exasol tooling (https://github.com/exasol/github-keeper), it is
required that matrix jobs define explcit job names.

Fixes #110

### CODE REVIEW

**Comment by Nicoretti** [comment]
@tkilias @redcatbear @tomuben 

Looks like the github action references always the latest version of  [integration-test-docker-environment](https://github.com/exasol/integration-test-docker-environment), but Exasol 6.x support there was dropped in [january 2022](https://github.com/exasol/integration-test-docker-environment/releases/tag/0.8.0). 

Do you know if can drop the support in the CI safely too?

To avoid such unnoticed failures in the future, we should consider some precautions like, e.g.:
* Pin the used integration-test-docker-environment version and add e.g. Dependabot for automated updates
* Make sure, a CI build is run automatically, every x (day/week/...). So a failing CI due to external changes will trigger a notification
* Add a pined version as dev dependency to the project
* ...

**Comment by redcatbear** [comment]
As discussed: we don't test against EoL versions.

**Comment by tkilias** [comment]
Yes, please pin the version during the clone to one the latest release tag and update the build matrix to 7.0.16 and 7.1.6. Please, also create a ticket for the weekly tests.

**Comment by tkilias** [comment]
We should maybe also add newer python versions to the test matrix

**Review by tkilias — APPROVED** [review]

**Review by kaklakariada — APPROVED** [review]

**Pull request merged**
