### PR TITLE
Add tests against latest bugfix versions of the Exasol DB to Github Actions

### PR DESCRIPTION
**Pull request by tkilias**
This pull requests adds the following Exasol Version to the test matrix:
          - 6.2.6-d1
          - 6.1.9-d1
          - 6.0.16-d1
These are the latest available docker image for bugfix versions for all still supported minor version of Exasol.

### CODE REVIEW

**Review by jank — APPROVED** [review]
@nndo1991 this looks good to me. I leave the merge to you as you are currently preparing the switch from Travis to GitHub Actions.

**Comment by fergarzag91** [comment]
Looks good

**Comment by fergarzag91** [comment]
@tkilias I cloned https://github.com/exasol/integration-test-docker-environment.git and tried to setup a local container just as our main.yml does in this project, but had no luck so far, I either get asked for Python 3.6 or have problems while running this inside a virtual environment.

Even though the Github Action runs as expected, for us is also important to be able to run these tests locally for whenever we bump dependencies or do small changes. 

Would it be possible for you to create a Dockerfile inside https://github.com/exasol/integration-test-docker-environment.git that automates all the setup and dependency installs? Main objective is to just build the image, run a container, and have the local Exasol env spawn

**Comment by tkilias** [comment]
@nndo1991 Fun fact, I started today with exactly this, but actually for another reason. Will continue with this tomorrow. Only, one small caveat, this thing will mount the docker socket, which works quite good under linux, under macosx okish from what I heard and windows is still questionable. The first version will be linux only, because I currently have non of the other two systems available.
Regarding Python 3.6, I thought I had removed this limitation, but might be that it was on another project.

**Comment by tkilias** [comment]
@nndo1991 ok, checked it and removed the Python 3.6 requirement. Virtual environment should be a problem, it uses pipenv to fetch install its dependencies and pipenv usually reuses activated virtual environments. Will add the Dockerfile anyway.

**Comment by fergarzag91** [comment]
@tkilias Thank you, I got past the Python 3.6 restriction but problem is still the same. Both docker containers are started but the DB fails to be spawn:

* 1 failed:
    - 1 SpawnTestEnvironmentWithDockerDB(...)

Might be linked to the fact that I'm running MacOSX. Anyways, once the Dockerfile is ready shouldn't be a problem to run it anywhere. Thanks for taking this task

**Comment by tkilias** [comment]
@nndo1991 Yes, MacOSX doesn't support the privileged mode for docker container. I totally forget that. The docker-db however requires the privileged mode to run. There is currently nothing we can do against this.
In case you tried the last 20 minutes or so to start it in the CI, I had a small mishap while removing the python 3.6 requirement. Should now work again. I am going to introduce stable tags soon, to avoid these problems in the future.

**Comment by tkilias** [comment]
> @tkilias Thank you, I got past the Python 3.6 restriction but problem is still the same. Both docker containers are started but the DB fails to be spawn:
> 
>     * 1 failed:
>       
>       * 1 SpawnTestEnvironmentWithDockerDB(...)
> 
> 
> Might be linked to the fact that I'm running MacOSX. Anyways, once the Dockerfile is ready shouldn't be a problem to run it anywhere. Thanks for taking this task

Hi @nndo1991,

it took a bit longer, but now the [integration-test-docker-environment](https://github.com/exasol/integration-test-docker-environment) per default starts a docker container to run the startup python script. To start the python script on the host, you can use another bash script ./start-test-env-without-docker-runner. I am going to derive from this version a stable version and a tag you can check out.

**Comment by fergarzag91** [comment]
Hi @tkilias not sure if I'm doing something wrong but got the same results. Pretty much I just copied the repo and then ran this:

`./start-test-env-without-docker-runner spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-port-forward 6666`

How ever, i got the same error. Is there anything I'm missing. Do I need to build the Dockerfile and run it?

**Comment by tkilias** [comment]
Hi @nndo1991,
so the database still won't work under MacOSX, because it needs privileged mode. If this is your problem, or do you have problems with python dependencies?

**Comment by fergarzag91** [comment]
I don't have any problem with dependencies. Is there a way that this can be run entirely on a Linux-based Docker contianer? That way I could get past the MacOSX conflict

**Comment by tkilias** [comment]
@nndo1991 ok, the privileged mode is necessary. There is currently, no way around. Could you try something for me, because I don't have a Mac to test it. Let's try to start a privileged container without the database and go from there. Maybe we have luck and it is not the privileged mode. 

To run container in privileged mode use the following command:

> docker run -it --privileged ubuntu:18.04 bash

And it would be helpful, if you could redirect the log of starting the test environment into a file and attach it.

**Comment by fergarzag91** [comment]
Hi @tkilias, I spent a bit more time trying to debug this and here's what I did:

1. Created a fresh container based on ubuntu:18.04, ran it as privileged
2. Installed all dependencies as described on this [Dockerfile](https://github.com/exasol/integration-test-docker-environment/blob/master/Dockerfile)
3. Ran the script inside container `./start-test-env-without-docker-runner spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-port-forward 6666`

The 2 underlying images are correctly fetched and their containers are correctly started, but the spawn process fails a couple times before maximum attempts to start the DB are reached. The error I keep getting while spawn is:

`'could not start database: system does not have enough active nodes or dwad was not able to create startup parameters for system'`

I'm attaching a full log since the moment I ran the script in step number 3, you will see the error 4 times in there, which I assume is raised somewhere in the code of the 2 underlying docker images.

Thanks!
[log.txt](https://github.com/blue-yonder/sqlalchemy_exasol/files/4726022/log.txt)

**Comment by tkilias** [comment]
Hi @nndo1991,
thanks, I have look at the log, maybe it gives me a clue what happens.

**Comment by tkilias** [comment]
@nndo1991 Actually, I probably need the whole log directory from inside the database container. I usually copy it with:

> docker cp \<container-name>:/exa/logs .

**Comment by fergarzag91** [comment]
Sorry for the delay @tkilias, got busy with other tasks yesterday. I'm attaching the full logs below.
[logs.zip](https://github.com/blue-yonder/sqlalchemy_exasol/files/4736933/logs.zip)

**Comment by tkilias** [comment]
Hi @nndo1991,

I took a look at the logs and found the error message. The db per default requested 4 GB RAM, but it seems that the VM for docker under MacOSX doesn't provide that much. I commited a new version of the test environment which only requests 2 GB per default and has a command line option to set the db-mem-size. However, the lowest possible value is 1 GB. So, maybe check also, if you can adjust the RAM of the Docker VM. Let me know if it still doesn't work and please provide again the logs.

**Comment by fergarzag91** [comment]
Hi @tkilias I pulled the new code and it resulted in the same error, then I changed my Docker configuration to allocate 4.25 GB and I got past the error.

How ever, now I'm getting a new error (attached full logs). The specific error is:
`Exception: Failed to populate the database with data.
    Log: cd /tests/test/enginedb_small; $EXAPLUS -c '172.24.0.2:8888' -u 'sys' -p 'exasol' -f import.sql
    bash: line 0: cd: /tests/test/enginedb_small: No such file or directory`

I noticed that when spawning the test_container_test container, the tests_src folder is empty, so the error below makes sense because /test/enginedb_small doesn't exist in the container.

[logs.zip](https://github.com/blue-yonder/sqlalchemy_exasol/files/4747759/logs.zip)

**Comment by tkilias** [comment]
Hi @nndo1991 ,

I probably know the problem here, but the solution is not so easy, because of that I added a new command line flag to the test environment to deactivate the database population. With `--deactivate-database-setup` you can deactivate this step and then it should run through.

I think, the problem here is, that I start the container from within a container, as such I am using the docker socket of the Docker VM. It looks like that Docker for Mac docker socket or client makes some translations of paths and maybe also some other stuff.
I think, this might also influence the port forwards. That a problem, because port forwards are the only way to access services in container from the host. https://docs.docker.com/docker-for-mac/networking/ 

Maybe, we need to revert the docker-runner for MacOSX to use the docker socket on the Mac side.

**Comment by fergarzag91** [comment]
@tkilias I see. I ran this again with the tag `--deactivate-database-setup` and it now worked. I was able to log into the database using DBVisualizar and run a couple queries. So this should be enough to be able to run our tests locally, but it would definitely be a good idea to get this working across all platforms.

For the record I also start the 2 containers within another container that I launch like this:
`docker run -v /var/run/docker.sock:/var/run/docker.sock -it --privileged exasol_docker`

Inside that container is where I execute `./start-test-env-without-docker-runner` and it now works.

One other thing to keep in mind is that this [Dockerfile](https://github.com/exasol/integration-test-docker-environment/blob/master/Dockerfile) is not copying the source code to the image, therefore once I start the container I have to manually do a git clone before being able to execute the `./start-test-env-without-docker-runner`.

Might also be a good idea to add a `COPY . /integration-test-docker-environment` step to the Dockerfile. What do you think?

**Comment by tkilias** [comment]
@nndo1991 I am going to think about it, the idea with the mounted directories was, that you easily can change the content of the tests directory and use it from the test container. There might be also a way to fix the failing mount. Can you try the following command send me the results:

`docker run -it --name docker_inspect_test -v "/var/run/docker.sock:/var/run/docker.sock" -v "$PWD:$PWD" exatk/script-languages-build-cache:build-container-aa06a53628a5544e50e14f01ee4d835a5f6c2b9b docker inspect docker_inspect_test`

This one mounts similar to start-test-env the docker socket and the current directory. Maybe, the docker inspect shows us what are the internal path for the mounts in the Docker VM.

**Comment by tkilias** [comment]
I also wrote down what found out until now, such that I can add to the Readme of the test environment.
https://github.com/exasol/integration-test-docker-environment/pull/16

**Comment by fergarzag91** [comment]
Hi @tkilias here's the output of that command:
[output.txt](https://github.com/blue-yonder/sqlalchemy_exasol/files/4761464/output.txt)

**Comment by tkilias** [comment]
@nndo1991 Thanks, the result is actually quite interesting. Can you check, if this is the path on the Mac side as well, because it is the path which gets mounted into the container.
`/local_path/Git_Projects/integration-test-docker-environment` . If it different it gets interesting.

And can you, run the last command also from inside a container, maybe this gives us more hints.

**Comment by fergarzag91** [comment]
Hi @tkilias sorry I didn't specify that I covered my paths, ips, and mac address out of security. But the real path is fine, is consistent across the whole log.

`/Users/name/..../Git_Projects/integration-test-docker-environment`

**Comment by tkilias** [comment]
@nndo1991 Ah ok, this explains the unexpected path. Its totally fine that you replaced path. Ok, then the paths are same in the VM and on Mac or the docker server in the VM is somehow modified to show the same path. If I remember correct, you tested to start a docker container from inside of a container with a mounted path and it worked. This means, I need to check, how I generate the paths for mounts in the test environment starter. Maybe, I am doing something which leads to invalid paths.

**Comment by tkilias** [comment]
@nndo1991 I am going to prepare tommorow a version which logs the used paths. Maybe, we see then what it is doing.

**Comment by tkilias** [comment]
@nndo1991 I think, I know now what's happening. I use the following line to get the absolute path. I think, this might give me slightly different results to what $PWD would give me on the host. So, I will add a parameter which allows me to pass the working directory from the host to the starter.

https://github.com/exasol/integration-test-docker-environment/blob/3ea81172248f770596d81ff378772677ab5656ea/src/lib/test_environment/spawn_test_container.py#L83

**Comment by tkilias** [comment]
Hi @nndo1991, 
I prepared a branch with the changes. Could you check out the branch `host_working_directory` and run `test_working_directory.sh` it starts the environment one time without the new parameter and another time with the parameter set to `$PWD` and filter each time the log for necessary information. 

**Note: please, mask your paths again, if you upload the output and check if the original paths are somehow between the two runs.**

Here also the link to branch:
https://github.com/exasol/integration-test-docker-environment/compare/host_working_directory

**Comment by fergarzag91** [comment]
Hi @tkilias I ran the file and it appears paths are identical in both runs. Attached:

[logs.txt](https://github.com/blue-yonder/sqlalchemy_exasol/files/4771806/logs.txt)

**Comment by tkilias** [comment]
Hi @nndo1991 ,

Can you check if it actually works with both variants, because the output of the script should contain error messages and Failed for at least one of the variants, but I don't see any. Maybe, we already solved it.

**Comment by fergarzag91** [comment]
@tkilias so I now understand the problem better and realized the issue was on my end. I just re-did all the steps I mentioned in [this](https://github.com/blue-yonder/sqlalchemy_exasol/pull/96#issuecomment-638439880) comment and everything worked. Rather than using `./start-test-env-without-docker-runner` I went straight for `./start-test-env` and it worked fine, didn't have to use `--deactivate-database-setup` or anything else.

The problem was that to get the source code up in the container I was doing a `git clone` inside it as I mentioned in [this](https://github.com/blue-yonder/sqlalchemy_exasol/pull/96#issuecomment-641451394) comment, instead of mounting my local directory as you correctly pointed out in the next comment. That caused the container not find the paths/env variables and therefore was not able to find the DB population scripts.

Now I executed the container mounting my local directory rather that doing the git clone:

`docker run -v /var/run/docker.sock:/var/run/docker.sock --volume $(pwd):$(pwd) --workdir $(pwd) -it --privileged exasol_docker`

Once up I installed docker on the container:

`apt install docker.io`

And finally ran the script:

`./start-test-env spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-port-forward 6666`

So as a summary, 2 actions solved this:

- Updated my docker config to allocate +4GB to each container
- Mounted my local directory (source code) to the container

Sorry I dragged you on this issue for so long and thanks for your patience, appreciate it 😁

**Comment by tkilias** [comment]
@nndo1991 I am happy to hear this. Yeah, if you cloned it in the docker container, it won't work. Yes, if you mount host directories to a docker container, it is always from the real host, also if you call the docker run from inside docker container with a mounted docker socket. Because, of the misunderstanding, I thought it would be somehow different on Mac, because of the VM. One tip, you don't need an own docker container, start-env-test will start one with all dependencies and the necessary mounts.

Thank you, for your patience, too. I am going to adjust the README of the environment and prepare a release.

**Pull request merged**
