### PR TITLE
Fix insert into statements (CTE - common table expression)

### LINKED ISSUE #55: Compiling INSERT/DELETE statements containing WITH clauses
If you have an insert statement containing a common table expression the compiling to string will fail. In a very simplified way:

```
from sqlalchemy import MetaData, Table, Column, Integer, select
metadata = MetaData()

table_A = Table("table_A", metadata,
              Column("int", Integer))
table_B = Table("table_B", metadata,
              Column("int", Integer))
table_C = Table("table_C", metadata,
              Column("int", Integer))

cte = select(
    columns=[table_A.c.int],
    from_obj=table_A).cte("cte")
query = select(
    columns=[table_B.c.int],
    from_obj=table_B.join(cte, onclause=table_B.c.int == cte.c.int))
insert = table_C.insert().from_select(['int'], query)
```

If you print the insert statement you will end up with

WITH cte AS
(SELECT "table_A".int AS int
FROM "table_A")
 INSERT INTO "table_C" (int) SELECT "table_B".int
FROM "table_B" JOIN cte ON "table_B".int = cte.int

But the EXASOL dialect will complain (syntax error, unexpected INSERT_, expecting SELECT_ or TABLE_ or VALUES_ or '(') because the expected syntax would be the WITH statement before the SELECT directly:

INSERT INTO "table_C" (int)
WITH cte AS
(SELECT "table_A".int AS int
FROM "table_A")
SELECT "table_B".int
FROM "table_B" JOIN cte ON "table_B".int = cte.int

### PR DESCRIPTION
**Pull request by vamega**
CTEs now follow insert into statements instead of preceding them.

This at least partially fixes #55

### CODE REVIEW

**Comment by jank** [comment]
@vamega thank you for your contribution. Did you find any test case of the SQLAlchemy test suite that fails (there are quite a number of tests deactivated) that succeeds with this addition? While test coverage is not perfect, it would be great to see this covered in a test case.
Alternatively, adding a test case to `test/test_exasol.py`would be great.

**Comment by jank** [comment]
There are actually a few CTE tests that are currently skipped (from a recent Travis build https://travis-ci.org/blue-yonder/sqlalchemy_exasol/jobs/568346163):

```
test/test_suite.py::CTETest::test_delete_from_round_trip SKIPPED         [ 14%]
test/test_suite.py::CTETest::test_delete_scalar_subq_round_trip SKIPPED  [ 15%]
test/test_suite.py::CTETest::test_insert_from_select_round_trip SKIPPED  [ 15%]
test/test_suite.py::CTETest::test_select_nonrecursive_round_trip SKIPPED [ 15%]
test/test_suite.py::CTETest::test_select_recursive_round_trip SKIPPED    [ 16%]
test/test_suite.py::CTETest::test_update_from_round_trip SKIPPED         [ 16%]
```

To enable these tests, the corresponding requirements need to be enabled (opened), e.g. in  `SuiteRequirements` CTE is disabled by default:

```
@property
    def ctes(self):
        """Target database supports CTEs"""

        return exclusions.closed()
```

**Comment by vamega** [comment]
@BY-jk I'll look into running these tests and comment here.
I expect I'll only really have the time to do this on the weekend, so I hope to have something to say this time next week.

**Comment by jank** [comment]
@vamega - your original commit left the requirement `closed`. On master I changed it to `open`, however the tests depend on the DB supporting `WITH RECURSIVE`. Thus the tests fail on EXASOL and I had to close them again.

**Comment by vamega** [comment]
Hi @BY-jk, I wasn't able to run the tests, since the travis set up does not run on Pull Requests.
I was going to set up a docker setup to run the tests over the weekend.

Too bad that CTE support assumes that `WITH RECURSIVE` is supported. I can investigate if there is a way to run the tests that do not support `WITH RECURSIVE` and will open a PR if I find something.

Thanks for merging this in!

**Comment by jank** [comment]
Have a look at the three docker file definitions in the root of the repo.
* base is meant to build the base image including required Debian packages
* SQLA builds on base to add the SQLA and all requirements
* the last docker file builds on SQLA to add the Exasol dialect
this layering was introduced to speed up iteration cycles, e.g. not requiring to rebuild the complete stack on each change. If you have a better alternative, please contribute.

**Pull request merged**
